<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64922" started-at="2015-06-09T14:57:32Z" finished-at="2015-06-09T14:58:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64922" started-at="2015-06-09T14:57:32Z" finished-at="2015-06-09T14:58:37Z">
      <class name="com.prannoy.testng2.maven.test.AppTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.prannoy.testng2.maven.test.AppTest@3cda1055]" name="beforeMethod" is-config="true" duration-ms="16399" started-at="2015-06-09T10:58:05Z" finished-at="2015-06-09T10:58:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="main()[pri:0, instance:com.prannoy.testng2.maven.test.AppTest@3cda1055]" name="main" duration-ms="14778" started-at="2015-06-09T10:58:21Z" finished-at="2015-06-09T10:58:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.prannoy.testng2.maven.test.AppTest@3cda1055]" name="afterMethod" is-config="true" duration-ms="441" started-at="2015-06-09T10:58:36Z" finished-at="2015-06-09T10:58:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.prannoy.testng2.maven.test.AppTest -->
      <class name="com.prannoy.testng2.maven.test.SplendorTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.prannoy.testng2.maven.test.SplendorTest@566776ad]" name="beforeMethod" is-config="true" duration-ms="24014" started-at="2015-06-09T10:57:32Z" finished-at="2015-06-09T10:57:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="main()[pri:0, instance:com.prannoy.testng2.maven.test.SplendorTest@566776ad]" name="main" duration-ms="8335" started-at="2015-06-09T10:57:56Z" finished-at="2015-06-09T10:58:04Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:149)
	at junit.framework.Assert.assertEquals(Assert.java:155)
	at com.prannoy.testng2.maven.test.SplendorTest.main(SplendorTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.prannoy.testng2.maven.test.SplendorTest@566776ad]" name="afterMethod" is-config="true" duration-ms="938" started-at="2015-06-09T10:58:04Z" finished-at="2015-06-09T10:58:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.prannoy.testng2.maven.test.SplendorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
